apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubequeuefunctions-deployment
spec:
  selector:
    matchLabels:
      app: kubequeuefunctions-pod
  template:
    metadata:
      labels:
        app: kubequeuefunctions-pod
    spec:
      containers:
        - name: kubequeuefunctions-container
          image: ghcr.io/arkapravasinha/kubequeuefunctions:v0.1.2
          env:
            - name: AzureWebJobstestlocalqueue
              valueFrom:
                secretKeyRef: null
                name: azure-storage-queue-secret
                key: ConnectionString
                optional: false
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 80
