apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: azure-storage-queue-consumer
spec:
  scaleTargetRef:
    deploymentName: kubequeuefunctions-deployment # must be in the same namespace as the ScaledObject
    containerName: kubequeuefunctions-container
  pollingInterval: 5   # Optional. Default: 30 seconds
  cooldownPeriod: 30   # Optional. Default: 300 seconds
  maxReplicaCount: 30  # Optional. Default: 100
  triggers:
  - type: azure-queue
    authenticationRef:
      name: azure-queue-auth
    metadata:
      queueName: testlocalqueue
      queueLength: "1"