apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-storage-queue-consumer
spec:
  scaleTargetRef:
    name: kubequeuefunctions-deployment                 #  <--- Property name was changed
    envSourceContainerName: kubequeuefunctions-container
  pollingInterval: 5   # Optional. Default: 30 seconds
  cooldownPeriod: 30   # Optional. Default: 300 seconds
  maxReplicaCount: 30  # Optional. Default: 100
  triggers:
  - type: azure-queue
    authenticationRef:
      name: azure-queue-auth
    metadata:
      queueName: testlocalqueue
      queueLength: "1"